services:
  nginx:
    restart: unless-stopped
    build: requirements/nginx
    volumes:
      - shared_volume:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpressphp
    secrets:
      - dninception.crt
      - dninception.key
      - dninception.dhparam.pem
      - fullchain.pem

  wordpressphp:
    restart: unless-stopped
    build: requirements/wordpress
    volumes:
      - shared_volume:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_wp_host
      - db_wp_admin
      - db_wp_pass
      - db_wp_email
      - db_wp_url

  mariadb:
    restart: unless-stopped
    build: requirements/mariadb
    volumes:
      - database_volume:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_user
      - db_name

volumes:
  shared_volume:
    driver_opts:
      type: none
      device: /home/$USER/data/shared_volume
      o: bind
  database_volume:
    driver_opts:
      type: none
      device: /home/$USER/data/database_volume
      o: bind

secrets:
  db_password:
    file: ../secrets/mysql_password.txt
  db_user:
    file: ../secrets/mysql_user.txt
  db_name:
    file: ../secrets/mysql_database.txt
  db_wp_host:
    file: ../secrets/wordpress_db_host.txt
  db_wp_admin:
    file: ../secrets/wordpress_admin_user.txt
  db_wp_pass:
    file: ../secrets/wordpress_admin_password.txt
  db_wp_email:
    file: ../secrets/wordpress_admin_email.txt
  db_wp_url:
    file: ../secrets/wordpress_url.txt
  dninception.crt:
    file: ../secrets/dninception.crt
  dninception.key:
    file: ../secrets/dninception.key
  dninception.dhparam.pem:
    file: ../secrets/dninception.dhparam.pem
  fullchain.pem:
    file: ../secrets/fullchain.pem
networks:
  dninception:
    driver: bridge